# Generated by Django 3.1.3 on 2020-11-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
