# Generated by Django 3.1.3 on 2020-11-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20201113_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
